# Generated by Django 2.2.3 on 2019-10-25 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescription_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='', max_length=100)),
                ('doctor_type', models.CharField(choices=[('audiologist', 'Audiologist'), ('allergist', 'Allergist'), ('anesthesiologist', 'Anesthesiologist'), ('cardiologist', 'Cardiologist'), ('dentist', 'Dentist'), ('dermatologist', 'Dermatologist'), ('endocrinologist', 'Endocrinologist'), ('epidemiologist', 'Epidemiologist'), ('gynecologist', 'Gynecologist'), ('immunologist', 'Immunologist'), ('infectious disease specialist', 'Infectious Disease Specialist'), (' medical geneticist', ' Medical Geneticist'), ('science fiction', 'Science fiction'), ('microbiologist', 'Microbiologist'), ('neonatologist', 'Neonatologist'), ('neurologist', 'Neurologist'), ('neurosurgeon', 'Neurosurgeon'), ('obstetrician', 'Obstetrician'), ('oncologist', 'Oncologist'), ('orthopedic surgeon', ' Orthopedic Surgeon'), ('eNT specialist', ' ENT Specialist'), ('pediatrician', 'Pediatrician'), ('physiologist', 'Physiologist'), ('plastic surgeon', 'Plastic Surgeon'), ('podiatrist', 'Podiatrist'), ('psychiatrist', 'Psychiatrist'), ('radiologist', 'Radiologist'), ('rheumatologist', 'Rheumatologist'), ('surgeon', 'Surgeon'), ('urologist', 'Urologist')], max_length=50)),
                ('doctor_phone', models.CharField(default='', max_length=15)),
                ('doctor_email', models.EmailField(default='', max_length=254)),
                ('doctor_designation', models.TextField(default='', max_length=600)),
                ('patient_name', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
                ('age', models.IntegerField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('disease', models.TextField(default='', max_length=300)),
                ('diagnosis', models.TextField(default='', max_length=300)),
                ('treatment_planning', models.TextField(default='', max_length=900)),
                ('next_visit_date', models.DateField(default='')),
                ('doctor_signature', models.CharField(default='', max_length=50)),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
